### ISSUE TITLE
Allow dynamic form logic with graphical button interaction

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#127]
Take a look at this [Demo](https://civiclaboratories.com/demo/bike-network-improvements) and hit the **"Share your thoughts"** button.

You'll see that instead of displaying the full form, it first prompts the user with a simple set of pretty buttons. Each button has a conditional set of form fields attached to it which only display depending on which button is selected.

This is far superior to the current "submit a report" [form](http://heyduwamish.org/place/new) on Hey Duwamish for two reasons

1) It only displays the form fields necessary for each option, allowing a much simpler data entry experience and allowing more complex types of data to be entered

2) It gets rid of the drop down option for "type of report" which users tend to ignore or not understand.

---

The goal of this issue ticket is to convert the "type of report" drop down menu into a button interface that functions like this:

* User adds a new report (form appears) 

* User is first asked to select a "report type" and has graphical buttons to choose from. 

* User selects the report type they want, and the form then interactively displays the necessary fields that are subsets of the specific report type selected.

---

The code for the example [demo](https://civiclaboratories.com/demo/bike-network-improvements) is available as a Planbox theme [here](https://github.com/openplans/planbox-themes/tree/gh-pages/bike-network-improvements)

The goal is to borrow the [place-form.html](https://github.com/openplans/planbox-themes/blob/gh-pages/bike-network-improvements/jstemplates/place-form.html) from the "Bike Network Improvements" Planbox Theme and use it in the [place-form.html](https://github.com/smartercleanup/duwamish/blob/master/src/flavors/duwamish_flavor/jstemplates/place-form.html) on Hey Duwamish.

The challenge lies in the fact that Hey Duwamish is based on [Shareabouts](http://github.com/openplans/shareabouts) and the Bike Network Improvements theme is based on [Planbox](http://github.com/openplans/planbox)

Planbox is similar to Shareabouts, but Shareabouts uses a [config.yml](https://github.com/smartercleanup/duwamish/blob/master/src/flavors/duwamish_flavor/config.yml) file for configuration and Planbox uses a [project.json](https://github.com/openplans/planbox-themes/blob/gh-pages/bike-network-improvements/project.json) file.

**Comment by LukeSwart** [comment]
The view that loads our "add a new place" form is under `src/sa_web/static/js/views/place-form-view.js`, which loads templates from `src/sa_web/jstemplates/place-form.html`. You can find all of our existing view and templates in those folders as well.

**Comment by LukeSwart** [comment]
I think the js view is in this repo: https://github.com/openplans/planbox

**Comment by LukeSwart** [comment]
Or in here: https://github.com/openplans/shareabouts.js/blob/master/src/place-form-view.js

**Comment by goldpbear** [comment]
I have a working initial version of this on goldpbear/dynamicFormLogic
