### ISSUE TITLE
Don't show the "about" page if user has already visited the site

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#172]
The default load page is http://heyduwamish.org/page/about which shows an "about" page pop-up. But if we can recognize that the user has visited the site already, we can assume that they have already seen the about page. Thus, we should not load the about page and let them get straight to mapping.

**Comment by futuresoup** [comment]
I notice users don't always close this about page and try to use Hey Duwamish with only half the map available! They also don't seem to read it very carefully.

Considering having this off by default and allowing users to click "about" if they are curious enough

**Comment by maxburto** [comment]
How about closing the welcome/about pullout when the user starts
interacting (clicking, dragging or selecting a map layer) with the map?
