### ISSUE TITLE
Add drawing tool to report form

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#181]
Any other options besides [Leaflet Draw](https://github.com/Leaflet/Leaflet.draw)?  [demo](http://leaflet.github.io/Leaflet.draw/)

We also want functionality so that depending what type of report people are drawing, the styling of the polygon looks different i.e. rain garden would have different polygon color scheme from community center

**Comment by goldpbear** [comment]
Closed, as this is covered by #410.
