### ISSUE TITLE
Refactor CSS to use a CSS generator

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#184]
Our CSS is currently under https://github.com/smartercleanup/duwamish/blob/master/src/sa_web/static/css/default.css and https://github.com/smartercleanup/duwamish/blob/master/src/flavors/duwamish_flavor/static/css/custom.css

It would be nice to refactor these to use something more clean and module, like Sass or Compass. We are open to suggestions too!

**Comment by LukeSwart** [comment]
From futuresoup (on the duplicate issue #232):

Our CSS is gigantic. We need a pre-processor to better organize and compile.

There's SASS
http://sass-lang.com/install

Compass
http://compass-style.org

LESS
http://lesscss.org/

And GUI apps like Koala to manage them:
http://koala-app.com/

**Comment by futuresoup** [comment]
@tlake is off to a good start on this branch - https://github.com/smartercleanup/platform/tree/tlake/sass-conversion

@jogit82 would be a great candidate to help on this! :)

**Comment by futuresoup** [comment]
All done except for #348
