### ISSUE TITLE
Strange mobile issues (!)

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#193]
One user has told us when trying to user her iphone6 on iOS 9.1

``I can only choose "observation" the button won't scroll to let me select others. Also, the Cancel button (can't remember for what?) remains on my screen and is frozen. And duplicates/remains on other pages too. I couldn't upload images either. Also, with the login- I thought I selected my Twitter to login, but it asked me again about logging in once I started to input info... I think. ``

**Comment by maxburto** [comment]
On the technical side the form looks like it is working on my end. The issue may be that the form elements are bellow the fold on mobile devices with medium or small screens, so users don't realise that if they scroll down after placeing their pin they can get to the rest of the form. Maybe right now we can give them an indication of where the rest of the form is by adding a message to the area where the "First drag the map to set your pin's location." message is. Maybe the message becomes visable after the user places their pin and the "First drag the map to set your pin's location." message is hidden and may say somthing like "Scroll down to finish your report."

**Comment by maxburto** [comment]
I added some styles that should help with this issue by keeping the place form type choise buttons in a 4x4 grid all the way down to small and medium devices.

**Comment by futuresoup** [comment]
This was an issue with the Chrome browser on the iPhone. We tested it on another iphone and we couldn't reproduce the freeze.

Marking as wontfix until we get more info and can reproduce on other devices
