### ISSUE TITLE
Change reporting workflow to address mobile space issues

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#197]
Due to limited screen size on mobile devices, we need to re-work the reporting workflow so that the pin location is selected first, and then the dynamic form interaction begins. 

The reason for this is that the form gets in the way of the map view and makes it difficult to select a location when the form window is obstructing the map.

The workflow should be:

1) User hits the ``Add a report`` button

2) User is prompted with a clear and obvious message on the screen that says ``First select the location of your report by dragging the map and placing the red pin``

Step #2 swaps out the current workflow of selecting a report type first, and then your location with the opposite. Location first, with it's own dedicated window display, then report type.

Once the location has been landed, the user doesn't need the map anymore and we can reduce the map view and dedicate the space toward optimizing the quality of their report.

**Comment by LukeSwart** [comment]
This is similar to issue #127, and I think we can use this demo: 
https://civiclaboratories.com/demo/bike-network-improvements/
which, I think, has the user experience that we are looking for. 

For example, when we select the "Add a report" button, we are immediately given a pin. And when a report type is selected, the location is saved without displaying the "first drag the map to set your pin's location" message again.
