### ISSUE TITLE
Create hide/show toggle switch for reports

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#231]
We need a way to hide and show reports on the map, so folks can view its features without all those eyeball pins getting in the way.

The URL to hide them is http://heyduwamish.org/filter/none

Then to show them again would be back to http://heyduwamish.org

---

We just need a simple switch to toggle these URLs back and forth on the sidebar or floating over the map somewhere

**Comment by LukeSwart** [comment]
Resolved in PR #319 

Eventually we want to filter reports by dataset and/or location type, but we will probably implement that functionality when the multi-dataset feature is shipped.
