### ISSUE TITLE
Better workflow for adding a report

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#256]
Recent user testing has revealed that first time users don't always notice the pin drop on the map and can't figure out the interaction they need to be doing when it comes to dragging the map and selecting a location. 

This has become a bigger problem recently, as there are lots of map features that cover up the red pin and make it hard to spot.

We need to improve this workflow a bit.

Some ideas
 * Darken the map and put a spotlight around the pin to isolate and highlight it as the active action
 * Eliminate all buttons and options on the report form except for the instructions on moving the new pin. Only show form options after first pin movement, where location is presumed to have been selected.

Important to note:
 * The interaction of dragging the map to move a pin is backwards from the norm. This is a good interaction once you're familiar with it (allows better map control to determine exact location), but it's not what people are used to. People tend to want to click areas of the map to mark their pin.

**Comment by goldpbear** [comment]
I have a version of the "spotlight" concept on the branch goldpbear/mapPinSpotlight.

**Comment by LukeSwart** [comment]
This issue was resolved by PR #277
