### ISSUE TITLE
fix placement of add a report button when content window is open

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#305]
When page view content i.e. http://heyduwamish.org/report/465 is open, the add a report button is in an awkward place.

For now, it should probably move over to bottom left while a page is open until we come up with a better design.

One future design idea is to hide the `add a report` button while page view content is open and insert it directly in the content itself. So you read the article and there's a button at the end that says "say something about this area" and then takes you straight to the reporting interface.

**Comment by LukeSwart** [comment]
@tlake I believe this was fixed here: https://github.com/smartercleanup/platform/commit/58d217cc0ee16440c687d188c5621bb61742258c

Is that correct?

**Comment by LukeSwart** [comment]
Fixed in #347
