### ISSUE TITLE
Add CSO data to our map

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#334]
Here is the map: http://www.kingcounty.gov/services/environment/wastewater/cso-status.aspx

And there is a repo on Github by Peter Keum with shows how to interact with the data behind that map.

It'd be nice to add the CSO status on Hey Duwamish.

**Comment by futuresoup** [comment]
We got it working on master!

Just a note - at some point Peter is going to move the URL off his personal github so we'll want to update it on our end when that happens
