### ISSUE TITLE
Storymap walkthrough feature

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#341]
The goal is to be able to navigate though various map features like a slideshow i.e.
https://storymap.knightlab.com/

For now we can just have an easy config setting:
```
Story:
  id: cleanup-sites
  order: reference-url1, reference-url2, etc.
```
For now we can start it as a javascript array, but in the future we likely want it to be in the actual django data model itself

**Comment by goldpbear** [comment]
Some thoughts on improvements to the story feature:

- Have two sets of story controls on a place detail view: one at the top of the view, and one at the bottom
- Use larger arrow buttons
- Use left and right chevrons instead of arrows

**Comment by futuresoup** [comment]
I've updated the arrows to be larger, and added some real content for South Park, but I am hitting a bug...

Sometimes the story won't advance to the next/previous story. Particularly when I load a story from a mobile sized responsive layout.

To reproduce:

* Resize the window so it is in a mobile sized responsive layout
* Click on ``/14th-ave`` (The heart icon along 14th Ave S. in South Park)
* Try to hit the next or previous arrow

The bug prevents this from happening in most cases, at least for me.

**Comment by goldpbear** [comment]
I've been playing around with the story mode at phone size, but so far haven't been able to reproduce the bug. Are you getting any messages appearing in the console?
