### ISSUE TITLE
Failed loading of landmarks via direct url

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#366]
On the `develop` branch, there seems to be a bug that sometimes prevents landmark detail views from being loaded when they're requested directly from the url bar (i.e. by navigating to something like `http://localhost:8000/lucile-and-holgate`).

I think the view might be trying to load before all the landmark models are fetched. When I set a short timeout on the code that renders the landmark details view, the landmark detail view will load correctly.

**Comment by LukeSwart** [comment]
Just confirming this bug, which can also be found on dev as well: http://dev.heyduwamish.org/lafarge-300000-pollution-fine

The dev server is currently deployed directly off of the `develop` branch. I suspect it is related to one of the changes we made here: https://github.com/smartercleanup/platform/pull/364/files#diff-14dd1494c6dc4edf68533be146d232b5L514

**Comment by goldpbear** [comment]
@LukeSwart It looks like you were on the right track here-- we were mistakenly referring to `self.options.landmarkConfigs`, when in fact the config arrays are contained in a object called `self.options.datasetConfigs.landmarks`, which was already being passed in to the app view.
