### ISSUE TITLE
Sporadic difficulties posting to multi datasets

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#381]
We occasionally get a strange error related to posting new reports when using the multi dataset feature -- something along the lines of underscore's `_.clone()` method being undefined I think.

These errors seem somewhat unpredictable, but I thought I would open an issue to collect discussion on them. @futuresoup -- if you run into an error like this, could you add any relevant info to this discussion?

**Comment by LukeSwart** [comment]
Is anyone else getting this error besides @futuresoup? If anyone else is having issues submitting new reports off of the `master` branch, then please let us know! Otherwise, I suspect something might be misconfigured on futuresoup's machine.

**Comment by futuresoup** [comment]
Closing this because this only seems to be happening in Versions before 0.7.0
