### ISSUE TITLE
"unsupported browser" warning in Microsoft Edge

### ISSUE THREAD

**Issue by futuresoup** [smartercleanup/platform#384]
Need to look into this, find out if we have features that are deprecated or not supported for Microsoft Edge, or whether this warning is generated for some other reason and can be easily turned off. 

Can folks with the latest Windows help us test?

**Comment by justBanks** [comment]
The unsupported browser message is triggered by code in sa_web/static/utils.js that can be easily turned off:
#398

**Comment by bil-io** [comment]
@justBanks  I see the code in there.
We may need to use something like this to decide what browser version are old 
https://codepen.io/gapcode/pen/vEJNZN
We can talk about it Wednesday at Open Seattle meeting or Thursday
