### ISSUE TITLE
Fix place list view filtering

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#414]
There is a lingering bug from the multidataset refactor that renders the `applyFilters()` method useless. It seems to affect some flavors but not others.

**Comment by LukeSwart** [comment]
This seems to be a duplicate of #383, no? 

Either way, I tested your PR #418 and it looks fixed!

**Comment by goldpbear** [comment]
Yes, most definitely a duplicate! Sorry, should have checked the issue list first
