### ISSUE TITLE
Lazily load map layers?

### ISSUE THREAD

**Issue by goldpbear** [smartercleanup/platform#436]
I believe we're loading all layers in the config when the map is initialized, including layers which are not visible by default (as per the `visibleDefault` flag in the config). We might want to lazily load layers as they are switched on by the user.

I did some **very** informal testing by commenting out layers one at a time and reloading the map.  Especially when layers are large (like the watershed layer and the river cleanup layer), it seems like we might get a noticeable performance boost by not initially loading switched-off layers.

**Comment by zmbc** [comment]
I am interested in doing this. It probably includes a refactor that would directly connect with the basemap stuff I did last night.

**Comment by goldpbear** [comment]
@zmbc yeah, go for it! Maybe it would make sense to abstract out all the layer initialization code into its own function, then call this function inside the `visibility` event callback inside `map-view.js` whenever a layer's visibility is toggled, checking to see if we've already loaded that layer.

It'll be interesting to see how this ultimately impacts load times.
