### ISSUE TITLE
Cannot post new places on develop-0.7.0

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#449]
We are getting this error when posting: 

>Place type undefined is not configured so it will not appear on the map.

Perhaps our config is not properly set up? This seems like it could be a rather simple bug!

Once we get this fix, and everything thoroughly tested, I think `develop-0.7.0` should be ready to merge!

BTW we can further test 0.7.0 on dev.heyduwamish.org.

**Comment by goldpbear** [comment]
I get this error as well on my machine, although it doesn't prevent me from submitting new places. It seems to be generated by the lack of a `location_type` property on a place model.

As far as I can tell, the `addLayerView` method in `map-views.js` is trying to create new `LayerView`s before the `location_type` property is attached to the model. `location_type` does eventually get attached, however, and can be found in the database.

This issue smells like it's related to the multidataset refactor. I'd have to study the original implementation a bit more to be totally sure, but I found that if we just set `location_type` explicitly when new models are added to their respective collection in the place form view then the error goes away.

I'll open a PR with this fix... @LukeSwart -- can you let me know if this fix allows you to post new places once it's up?
