### ISSUE TITLE
Basemaps on maps without legends don't work in develop-0.7.0

### ISSUE THREAD

**Issue by zmbc** [smartercleanup/platform#453]
Whoops. This is due to my own change: PR #440. Specifically, basemaps are now set to be visible or not using `visibleDefault` in the legend config, just like other types of layers. This (obviously) is not an option when there is no legend config.

If there isn't a legend, we can assume that all layers are visible, right? We don't currently do that. The only reason this issue doesn't exist in 0.6.0 is that we special-case tile layers [here](https://github.com/smartercleanup/platform/blob/746e8ba6c17827341ee64b9904eb542360623b5c/src/sa_web/static/js/views/map-view.js#L100). (Incidentally, we also special-case basemaps [here](https://github.com/smartercleanup/platform/blob/746e8ba6c17827341ee64b9904eb542360623b5c/src/sa_web/static/js/views/map-view.js#L74-L76), but as far as I can tell we never actually used that config option)

**Comment by LukeSwart** [comment]
>If there isn't a legend, we can assume that all layers are visible, right?

Yup, I think that's reasonable. I should have seen this one coming too! Thanks for the catch.
