### ISSUE TITLE
Hide the sidebar as default, with a pull-out tab option

### ISSUE THREAD

**Issue by LukeSwart** [smartercleanup/platform#53]
We need to implement a hide and reveal feature for the sidebar.

Here are some mockups provided by [Emily Danchik](emilydanchik.com/) as a reference. For now, we don't need to make the full UI changes illustrated in the mockups, just a simple arrow tab to hide and show the sidebar will do.

**Comment by LukeSwart** [comment]
![image](https://cloud.githubusercontent.com/assets/4207017/7107906/379bc1c0-e129-11e4-8486-628d113d2cb7.png)


![image](https://cloud.githubusercontent.com/assets/4207017/7107904/2ead2202-e129-11e4-83ae-9de066d89797.png)

**Comment by LukeSwart** [comment]
I believe the div id for that sidebar is `#side-bar`, so it should be doable through the CSS. Note that the side bar contains another div called `#master-legend`. The view is rendered under `legend-view.js`, and under `base.html` here: https://github.com/smartercleanup/duwamish/blob/master/src/sa_web/templates/base.html#L128-L141

The current state of the sidebar's html is pretty rough because the sidebar does not have it's own template. This is noted in issue #136. I am happy to work with someone to get both of these issues resolved.

**Comment by futuresoup** [comment]
Hey @ammiranda just a heads up: 

@maxburto appears to be resolving this by using the leaflet plugin described on issue #89 

Basically, if we want, we can load the Activity Stream into one of the icon sets i.e. the human looking one that can represent community activity. Then we can add more icon sets down the sidebar to symbolize other filters, GIS layer groupings, etc.

I suggest checking out his branch and working with him on it because I think it might make more sense.

**Comment by LukeSwart** [comment]
I have abstracted Max's work on this issue into this commit: https://github.com/smartercleanup/duwamish/commit/65072c23ebe9daeb3d032307cf133aa08d51f1a4

which was implemented using jquery. I had to undo that implementation because it was not ready yet for deployment. The hide/show button should be on the right and the slide would ideally be a smooth transition.

One can resume this sidebar hide/show toggle implementation by reverting that commit.

**Comment by LukeSwart** [comment]
I believe this was resolved in #293 which was implemented using the leaflet plugin.

There are definitely some open design considerations on the sidebar, and if we want to brainstorm them, then I think we should open a new issue that references this issue.
